#ifndef CODEC2_HAVE_VERSION
#define CODEC2_HAVE_VERSION

#define CODEC2_VERSION_MAJOR 1
#define CODEC2_VERSION_MINOR 0
#define CODEC2_VERSION_PATCH 3
#define CODEC2_VERSION "1.0.3"

#endif //CODEC2_HAVE_VERSION